"""add to users: username, phone, first name, second name

Revision ID: 8d0082e4bc30
Revises: 484e2249f443
Create Date: 2025-05-04 00:35:12.254872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d0082e4bc30"
down_revision: Union[str, None] = "484e2249f443"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=200), nullable=False))
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("second_name", sa.String(length=200), nullable=False)
    )
    op.add_column(
        "users", sa.Column("phone_number", sa.String(length=11), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phone_number")
    op.drop_column("users", "second_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
