"""make username, fisrt,second name, phone_number can be null

Revision ID: 11fc18b81e7c
Revises: 8d0082e4bc30
Create Date: 2025-05-04 01:32:50.125744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "11fc18b81e7c"
down_revision: Union[str, None] = "8d0082e4bc30"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "users", "second_name", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    op.alter_column(
        "users", "phone_number", existing_type=sa.VARCHAR(length=11), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "phone_number", existing_type=sa.VARCHAR(length=11), nullable=False
    )
    op.alter_column(
        "users", "second_name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "users", "first_name", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    # ### end Alembic commands ###
